### ISSUE TITLE
Add dependency to catch and flatbuffers

### ISSUE THREAD

**Issue by drodri** [yacoder/flatbuffers-with-spirit#1]
It seems that the dependencies to Catch and Flatbuffers are not actually handled by biicode, but both of them are already available there. Would like to know if there is any specific problem about it. I might try to help setting them if you want.

**Comment by yacoder** [comment]
Thanks, @drodri. I actually don't depend on flatbuffers :) I'm trying to emulate some of their parsing/generating logic... As for Catch, yes, it's interesting, how can I depend on it and will it work, when the "main()" function is coming from an external block?

**Comment by drodri** [comment]
There are a couple of Catch implementations in biicode, I would try to use FlorianWalters. It contains also the single header, which I would say is the same that you are using, so you can try to use it. 

https://www.biicode.com/florianwolters/florianwolters/catch/master/0/single_include/catch.hpp

So just write 

```
#include "catch.hpp"
```

and in your biicode.conf:

```
[requirements]
     florianwolters/catch: 0

[includes]
     catch.hpp: florianwolters/catch/single_include
```

Can you please give me more detail about your tests setup? will the main() function of the external block be an "open" block or a dependency. What is your layout, the one you currently have in your repo? I would say it should work as is, but please try it and tell me.

**Comment by yacoder** [comment]
@drodri, I meant that issue with Catch that "main()" function is actually defined inside the catch.hpp, not in my main.cpp...

I made the changes in biicode.conf as you suggested, but that block tries to build something inside it, and fails...

> [ 12%] Building CXX object       florianwolters_catch/CMakeFiles/florianwolters_catch.dir/projects/SelfTest/TestMain.cpp.obj
> florianwolters_catch\CMakeFiles\florianwolters_catch.dir\build.make:54: recipe for target 'florianwolters_catch/CMakeFiles/florianwolters_catch.dir/projects/SelfTest/TestMain.cpp.obj' failed

**Comment by yacoder** [comment]
Using diego/catch instead worked for me... However, it's odd that during the build a lib is produced for the catch block. I would like to just include the header, it doesn't need to be built / linked... However, I pushed the updated version with the dependency, and so I'm closing this issue...

**Comment by drodri** [comment]
It is expected, up to biicode 2.8, libs created a cmake_dummy.cpp, to avoid the problem of header only libs, and always created a lib. From biicode>2.8, now we are using INTERFACE libs of CMake more thoroughly and it is not necessary. 
You can check in: https://www.biicode.com/diego/diego/catch/master/0/CMakeLists.txt
There is a ADD_BIICODE_TARGETS(). The new command (the old one is maintained for retro compatibility) is ADD_BII_TARGETS(), and that will not create the lib. I will update it asap.

**Comment by drodri** [comment]
I have updated it, please try it (simply bii build should update the dependency to Catch automatically as it is a DEV version). 

You can check in https://www.biicode.com/diego/diego/catch/master/0/biicode.conf that I mark the file "catch.cpp" to NOT be defined as a main, as it is actually not an entry point, but intended to be included. If you have other files that do not have a main() but they are an entry point (should build an EXE) because they #include another file that actually has the main(), you can add them to the [mains] section.

**Comment by yacoder** [comment]
Works great! I had to do a `bii clean`, but after that everything worked automatically, and without unnecessary obj files. Thanks!!! :+1:  :)

**Comment by drodri** [comment]
:+1: Not at all :)
